algo: rainbow
data_dir: ./data
output_dir: /root/autodl-tmp/resilence/outputs/baselines_eval/rainbow
model_dir: /root/autodl-tmp/resilence/outputs/baselines_eval/rainbow
damaged_ratio: 0.3
assignment_iters: 60
assignment_method: cfw
use_cugraph: false
sp_backend: torch
force_gpu_sp: true
episodes: 2000
buffer_size: 1000000
batch_start: 2000
batch_size: 512
num_workers: 20
reward_scale: 0.05
reward_mode: minimize_tstt
reward_alpha: 1.0
reward_beta: 0.0
reward_gamma: 0.0
reward_clip: 2.0
capacity_damage: 1.0e-3
unassigned_penalty: 1.0e4
max_steps: 100
gat_layers: 3
eval_every: 20
hidden_dim: 256
embed_dim: 256
lr: 0.0003
gamma: 0.99
double_q: true
dueling: true
noisy: true
n_step: 3
num_atoms: 51
v_min: -200000.0
v_max: 200000.0
seed: 42
eval_seeds: [43, 44, 45, 46, 47, 48, 49, 50, 51, 52]
use_torch_bpr: true
device: cuda
save_best: true
eval_baselines: false
